/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GuardianRouteImport } from './routes/guardian'
import { Route as FamilyRouteImport } from './routes/family'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as BlockedRouteImport } from './routes/blocked'
import { Route as AlertRouteImport } from './routes/alert'
import { Route as AiMonitorRouteImport } from './routes/ai-monitor'
import { Route as IndexRouteImport } from './routes/index'

const GuardianRoute = GuardianRouteImport.update({
  id: '/guardian',
  path: '/guardian',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilyRoute = FamilyRouteImport.update({
  id: '/family',
  path: '/family',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const BlockedRoute = BlockedRouteImport.update({
  id: '/blocked',
  path: '/blocked',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertRoute = AlertRouteImport.update({
  id: '/alert',
  path: '/alert',
  getParentRoute: () => rootRouteImport,
} as any)
const AiMonitorRoute = AiMonitorRouteImport.update({
  id: '/ai-monitor',
  path: '/ai-monitor',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-monitor': typeof AiMonitorRoute
  '/alert': typeof AlertRoute
  '/blocked': typeof BlockedRoute
  '/community': typeof CommunityRoute
  '/demo': typeof DemoRoute
  '/family': typeof FamilyRoute
  '/guardian': typeof GuardianRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-monitor': typeof AiMonitorRoute
  '/alert': typeof AlertRoute
  '/blocked': typeof BlockedRoute
  '/community': typeof CommunityRoute
  '/demo': typeof DemoRoute
  '/family': typeof FamilyRoute
  '/guardian': typeof GuardianRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-monitor': typeof AiMonitorRoute
  '/alert': typeof AlertRoute
  '/blocked': typeof BlockedRoute
  '/community': typeof CommunityRoute
  '/demo': typeof DemoRoute
  '/family': typeof FamilyRoute
  '/guardian': typeof GuardianRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-monitor'
    | '/alert'
    | '/blocked'
    | '/community'
    | '/demo'
    | '/family'
    | '/guardian'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-monitor'
    | '/alert'
    | '/blocked'
    | '/community'
    | '/demo'
    | '/family'
    | '/guardian'
  id:
    | '__root__'
    | '/'
    | '/ai-monitor'
    | '/alert'
    | '/blocked'
    | '/community'
    | '/demo'
    | '/family'
    | '/guardian'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiMonitorRoute: typeof AiMonitorRoute
  AlertRoute: typeof AlertRoute
  BlockedRoute: typeof BlockedRoute
  CommunityRoute: typeof CommunityRoute
  DemoRoute: typeof DemoRoute
  FamilyRoute: typeof FamilyRoute
  GuardianRoute: typeof GuardianRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/guardian': {
      id: '/guardian'
      path: '/guardian'
      fullPath: '/guardian'
      preLoaderRoute: typeof GuardianRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family': {
      id: '/family'
      path: '/family'
      fullPath: '/family'
      preLoaderRoute: typeof FamilyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blocked': {
      id: '/blocked'
      path: '/blocked'
      fullPath: '/blocked'
      preLoaderRoute: typeof BlockedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alert': {
      id: '/alert'
      path: '/alert'
      fullPath: '/alert'
      preLoaderRoute: typeof AlertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-monitor': {
      id: '/ai-monitor'
      path: '/ai-monitor'
      fullPath: '/ai-monitor'
      preLoaderRoute: typeof AiMonitorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiMonitorRoute: AiMonitorRoute,
  AlertRoute: AlertRoute,
  BlockedRoute: BlockedRoute,
  CommunityRoute: CommunityRoute,
  DemoRoute: DemoRoute,
  FamilyRoute: FamilyRoute,
  GuardianRoute: GuardianRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
