/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransferRouteImport } from './routes/transfer'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RiskScoreRouteImport } from './routes/risk-score'
import { Route as PaymentSuccessRouteImport } from './routes/payment-success'
import { Route as MeRouteImport } from './routes/me'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HomeRouteImport } from './routes/home'
import { Route as BlockedRouteImport } from './routes/blocked'
import { Route as AlertRouteImport } from './routes/alert'
import { Route as AiMonitorRouteImport } from './routes/ai-monitor'
import { Route as IndexRouteImport } from './routes/index'

const TransferRoute = TransferRouteImport.update({
  id: '/transfer',
  path: '/transfer',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RiskScoreRoute = RiskScoreRouteImport.update({
  id: '/risk-score',
  path: '/risk-score',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentSuccessRoute = PaymentSuccessRouteImport.update({
  id: '/payment-success',
  path: '/payment-success',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const BlockedRoute = BlockedRouteImport.update({
  id: '/blocked',
  path: '/blocked',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertRoute = AlertRouteImport.update({
  id: '/alert',
  path: '/alert',
  getParentRoute: () => rootRouteImport,
} as any)
const AiMonitorRoute = AiMonitorRouteImport.update({
  id: '/ai-monitor',
  path: '/ai-monitor',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-monitor': typeof AiMonitorRoute
  '/alert': typeof AlertRoute
  '/blocked': typeof BlockedRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/me': typeof MeRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/risk-score': typeof RiskScoreRoute
  '/settings': typeof SettingsRoute
  '/transfer': typeof TransferRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-monitor': typeof AiMonitorRoute
  '/alert': typeof AlertRoute
  '/blocked': typeof BlockedRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/me': typeof MeRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/risk-score': typeof RiskScoreRoute
  '/settings': typeof SettingsRoute
  '/transfer': typeof TransferRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-monitor': typeof AiMonitorRoute
  '/alert': typeof AlertRoute
  '/blocked': typeof BlockedRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/me': typeof MeRoute
  '/payment-success': typeof PaymentSuccessRoute
  '/risk-score': typeof RiskScoreRoute
  '/settings': typeof SettingsRoute
  '/transfer': typeof TransferRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-monitor'
    | '/alert'
    | '/blocked'
    | '/home'
    | '/login'
    | '/me'
    | '/payment-success'
    | '/risk-score'
    | '/settings'
    | '/transfer'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-monitor'
    | '/alert'
    | '/blocked'
    | '/home'
    | '/login'
    | '/me'
    | '/payment-success'
    | '/risk-score'
    | '/settings'
    | '/transfer'
  id:
    | '__root__'
    | '/'
    | '/ai-monitor'
    | '/alert'
    | '/blocked'
    | '/home'
    | '/login'
    | '/me'
    | '/payment-success'
    | '/risk-score'
    | '/settings'
    | '/transfer'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiMonitorRoute: typeof AiMonitorRoute
  AlertRoute: typeof AlertRoute
  BlockedRoute: typeof BlockedRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  MeRoute: typeof MeRoute
  PaymentSuccessRoute: typeof PaymentSuccessRoute
  RiskScoreRoute: typeof RiskScoreRoute
  SettingsRoute: typeof SettingsRoute
  TransferRoute: typeof TransferRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transfer': {
      id: '/transfer'
      path: '/transfer'
      fullPath: '/transfer'
      preLoaderRoute: typeof TransferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risk-score': {
      id: '/risk-score'
      path: '/risk-score'
      fullPath: '/risk-score'
      preLoaderRoute: typeof RiskScoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-success': {
      id: '/payment-success'
      path: '/payment-success'
      fullPath: '/payment-success'
      preLoaderRoute: typeof PaymentSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blocked': {
      id: '/blocked'
      path: '/blocked'
      fullPath: '/blocked'
      preLoaderRoute: typeof BlockedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alert': {
      id: '/alert'
      path: '/alert'
      fullPath: '/alert'
      preLoaderRoute: typeof AlertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-monitor': {
      id: '/ai-monitor'
      path: '/ai-monitor'
      fullPath: '/ai-monitor'
      preLoaderRoute: typeof AiMonitorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiMonitorRoute: AiMonitorRoute,
  AlertRoute: AlertRoute,
  BlockedRoute: BlockedRoute,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  MeRoute: MeRoute,
  PaymentSuccessRoute: PaymentSuccessRoute,
  RiskScoreRoute: RiskScoreRoute,
  SettingsRoute: SettingsRoute,
  TransferRoute: TransferRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
